### ISSUE TITLE
No hosts fetched

### ISSUE THREAD

**Issue by eisiv** [gomorpheus/ansible-collection-morpheus-core#1]
Hi,
Seems like after some updates that the plugin doesn't fetch any hosts from Morpheus, though it does create the hostgroups.
Do you have time for a call, since this always seems easier to resolve that way?

**Comment by tryfan** [comment]
Is there any data you can provide?  Possibly some debug output, or cli testing for this issue?

**Comment by eisiv** [comment]
root@S700LS001:/var/tmp# ansible-inventory -i morpheusinv.yml --list -vvvv --vau                                                                              lt-password-file /var/opt/morpheus/morpheus-ui/ansiblevault/vault.txt
ansible-inventory [core 2.11.6]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share                                                                              /ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansibl                                                                              e
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/co                                                                              llections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
No config file found; using defaults
setting up inventory plugins
host_list declined parsing /var/tmp/morpheusinv.yml as it did not pass its verif                                                                              y_file() method
script declined parsing /var/tmp/morpheusinv.yml as it did not pass its verify_f                                                                              ile() method
Trying secret FileVaultSecret(filename='/var/opt/morpheus/morpheus-ui/ansiblevau                                                                              lt/vault.txt') for vault_id=default
Trying secret FileVaultSecret(filename='/var/opt/morpheus/morpheus-ui/ansiblevau                                                                              lt/vault.txt') for vault_id=default
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWar                                                                              ning: Unverified HTTPS request is being made to host 'ais.equinor.com'. Adding c                                                                              ertificate verification is strongly advised. See: https://urllib3.readthedocs.io                                                                              /en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
Parsed /var/tmp/morpheusinv.yml inventory source with auto plugin
{
    "_meta": {
        "hostvars": {}
    },
    "all": {
        "children": [
            "LinuxCentosPatch1",
            "LinuxLegacy",
            "UbuntuPatch1",
            "WindowsLegacy",
            "WindowsPatchGroup1",
            "WindowsPatchGroup2",
            "WindowsPatchGroup3",
            "WindowsPatchGroup4",
            "WindowsPatchGroup5",
            "WindowsPatchGroup6",
            "ungrouped"
        ]
    }
}

**Comment by tryfan** [comment]
What version of Morpheus are you on?  I found an issue with version detection, but I've been testing against newer builds.

**Comment by eisiv** [comment]
We're on 5.4.1

**Comment by tryfan** [comment]
Ok, I can test on that version.  Can you share the scrubbed inventory file itself?

**Comment by eisiv** [comment]
plugin: morpheus_inventory
groups:
  - name: WindowsPatchGroup1
    searchtype: tag
    searchstring:
      tagName: Patch
      tagValue: PatchGroup1

  - name: WindowsPatchGroup2
    searchtype: tag
    searchstring:
      tagName: Patch
      tagValue: PatchGroup2

  - name: WindowsPatchGroup3
    searchtype: tag
    searchstring:
      tagName: Patch
      tagValue: PatchGroup3

  - name: WindowsPatchGroup4
    searchtype: tag
    searchstring:
      tagName: Patch
      tagValue: PatchGroup4

  - name: WindowsPatchGroup5
    searchtype: tag
    searchstring:
      tagName: Patch
      tagValue: PatchGroup5

  - name: WindowsPatchGroup6
    searchtype: tag
    searchstring:
      tagName: Patch
      tagValue: PatchGroup6

  - name: LinuxCentosPatch1
    searchtype: tag
    searchstring:
      tagName: Patch
      tagValue: Linux Centos Patch1

  - name: UbuntuPatch1
    searchtype: tag
    searchstring:
      tagName: Patch
      tagValue: Ubuntu Patch1

  - name: LinuxLegacy
    searchtype: tag
    searchstring:
      tagName: PatchGroup
      tagValue: Linux

  - name: WindowsLegacy
    searchtype: tag
    searchstring:
      tagName: PatchGroup
      tagValue: PatchGroup1

morpheus_url: https://URL_HERE/
morpheus_api_key: 
morpheus_ssl_verify: no

**Comment by tryfan** [comment]
So, there's a few issues that I've found.  I tested with Ubuntu 20.04, Morpheus 5.4.1-2, ansible-core 2.11.6.  

In your example, you are referencing the plugin using `morpheus_inventory`.  In Ansible > 2.9, plugins are usually referenced by the FQCN, which in this case is `morpheus.core.morpheus_inventory`.  You can confirm by using `ansible-doc -t inventory -l` as the morpheus-local user.  My output for that is in the gist.

I installed the ansible collection as the morpheus-local user: `ansible-galaxy collection install morpheus.core`.  I created an inventory file referencing tags and got a successful return.

The issue I did run into is this:
```
[WARNING]:  * Failed to parse /opt/morpheus/.local/inv.yml with auto plugin: Invalid value "morpheus.core.morpheus_inventory" for configuration option "plugin_type:
inventory plugin: ansible_collections.morpheus.core.plugins.inventory.morpheus_inventory setting: plugin ", valid values are: ['morpheus_inventory']
```

I'm going to fix that issue and update the collection.  The workaround is to modify the `DOCUMENTATION` block on line 24 of `morpheus/core/plugins/inventory/morpheus_inventory.py` and add to the `choices:` entry:

`choices: ['morpheus_inventory', 'morpheus.core.morpheus_inventory']`

Gist with output: https://gist.github.com/tryfan/9ff4e68f1a9c4130db11400390d189c6

**Comment by eisiv** [comment]
Tried updating that line, no errors with the FQCN atleast, but still no hosts being fetched.
I'm wondering wether this also requires the Ansible plugin to be configured on all subtenants, or shouldn't that matter?

**Comment by eisiv** [comment]
Made sure that it's using the correct plugin version, but still no dice.

**Comment by tryfan** [comment]
Issue has been resolved
