### ISSUE TITLE
Read variable for morpheus url

### ISSUE THREAD

**Issue by eisiv** [gomorpheus/ansible-collection-morpheus-core#32]
Hey, just wondering if it's possible to read a variable, or read the morpheus appliance url instead of supplying the url?

**Comment by tryfan** [comment]
If the plugin is being run from Morpheus, it will use `morpheus['morpheus']['applianceUrl']` and `morpheus['morpheus']['apiAccessToken']`.  If you add `-vv` to the command options for the ansible task, it will output `Using ephemeral Morpheus token from Morpheus task` to let you know that it's found and is using the token.

**Comment by eisiv** [comment]
It seems like the task isn't picking up the token nor the appliance url, even though it says so with the -vv flag, it fails because no hosts are matched, though it does work if you supply url and token.

**Comment by eisiv** [comment]
Even weirder is when I supply the url and token in our test environment, it seems to be reading the wrong appliance_url, and targeting production, so I'm not sure if that has something to do with how our test environment was created(DB copy), or something else.

**Comment by eisiv** [comment]
Okay, so it works fine when run as a task, but not when run as a workflow, anything you're able to reproduce perhaps?

**Comment by tryfan** [comment]
I've run a test with the plugin using the api key supplied by morpheus.   I'm using an operational workflow.  I was getting a bad token error, but it only happened once, and I haven't been able to reproduce it.  Perhaps you'll have better luck.  I inserted 2 lines before line 78 in `morpheus_inventory.py`:
```
        self.print_verbose_message(self.extravars['morpheus']['morpheus'])
        self.print_verbose_message(returned_v)
```
That will show you the ephemeral token the task is being given, as well as any error from the version query, which is the first time the plugin tries to use the token.
